### ISSUE TITLE
os x  10.11 | ruby 1.9.3+

### ISSUE THREAD

**Issue by w-zengtao** [opentox/openbabel-gem#3]
> /Users/ztao/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/fileutils.rb:1515:in `stat': No such file or directory - /Users/ztao/.rvm/gems/ruby-1.9.3-p551/gems/openbabel-2.3.2.1/openbabel-2.3.2/scripts/ruby/openbabel.bundle (Errno::ENOENT)

this cause a problem that this gem can not create Makefile than can not auto compile

**Comment by helma** [comment]
We have updated to Version 2.3.2.2 which uses the Github Version of OpenBabel, which solves some InChI related bugs and simplifies the installation routine. I am however not sure if it works on OS X, as we only have access to Linux machines. Please reopen the issue, if the problem persists.
